Fix PytestUnraisableExceptionWarning
pytest reports a warning in tests/api/build.py::TestNucBuilder

  AttributeError: 'Indexed' object has no attribute 'molecule'

Since 'molecule' seems to be an optional member of the chempy Indexed
object, the AttributeError can be deliberately ignored.